export const companies=[
  {
    "id": "1",
    "name": "apple",
    "full_name": "Apple",
    "data": [
        {
          "date": "2023-01-01",
          "media": 234,
          "follows": 234,
          "followed_by": 35,
          "reach": 4000,
          "positive_sentiment": 0.5,
          "negative_sentiment": 0.3,
          "engagement_rate": 0.08,
          "impressions": 6000,
          "comments": 20,
          "shares": 15,
          "click_through_rate": 0.02,
          "average_likes": 50,
          "average_comments": 5
        },
        {
          "date": "2023-02-01",
          "media": 189,
          "follows": 189,
          "followed_by": 42,
          "reach": 3500,
          "positive_sentiment": 0.6,
          "negative_sentiment": 0.2,
          "engagement_rate": 0.1,
          "impressions": 8000,
          "comments": 25,
          "shares": 12,
          "click_through_rate": 0.03,
          "average_likes": 60,
          "average_comments": 8
        },
        {
          "date": "2023-03-01",
          "media": 300,
          "follows": 300,
          "followed_by": 50,
          "reach": 5000,
          "positive_sentiment": 0.7,
          "negative_sentiment": 0.1,
          "engagement_rate": 0.12,
          "impressions": 7500,
          "comments": 30,
          "shares": 18,
          "click_through_rate": 0.04,
          "average_likes": 70,
          "average_comments": 10
        },
        {
          "date": "2023-04-01",
          "media": 150,
          "follows": 150,
          "followed_by": 25,
          "reach": 3000,
          "positive_sentiment": 0.4,
          "negative_sentiment": 0.4,
          "engagement_rate": 0.06,
          "impressions": 4500,
          "comments": 15,
          "shares": 10,
          "click_through_rate": 0.01,
          "average_likes": 40,
          "average_comments": 3
        },
        {
          "date": "2023-05-01",
          "media": 270,
          "follows": 270,
          "followed_by": 40,
          "reach": 4500,
          "positive_sentiment": 0.8,
          "negative_sentiment": 0.05,
          "engagement_rate": 0.15,
          "impressions": 7000,
          "comments": 35,
          "shares": 20,
          "click_through_rate": 0.05,
          "average_likes": 80,
          "average_comments": 12
        },
        {
          "date": "2023-05-02",
          "media": 280,
          "follows": 280,
          "followed_by": 42,
          "reach": 4700,
          "positive_sentiment": 0.82,
          "negative_sentiment": 0.06,
          "engagement_rate": 0.16,
          "impressions": 7200,
          "comments": 37,
          "shares": 22,
          "click_through_rate": 0.06,
          "average_likes": 82,
          "average_comments": 14
        },
        {
          "date": "2023-05-03",
          "media": 290,
          "follows": 290,
          "followed_by": 45,
          "reach": 4900,
          "positive_sentiment": 0.85,
          "negative_sentiment": 0.07,
          "engagement_rate": 0.17,
          "impressions": 7500,
          "comments": 40,
          "shares": 25,
          "click_through_rate": 0.07,
          "average_likes": 85,
          "average_comments": 16
        },
        {
          "date": "2023-05-04",
          "media": 300,
          "follows": 300,
          "followed_by": 48,
          "reach": 5100,
          "positive_sentiment": 0.88,
          "negative_sentiment": 0.08,
          "engagement_rate": 0.18,
          "impressions": 7800,
          "comments": 42,
          "shares": 28,
          "click_through_rate": 0.08,
          "average_likes": 88,
          "average_comments": 18
        },
        {
          "date": "2023-05-05",
          "media": 310,
          "follows": 310,
          "followed_by": 50,
          "reach": 5300,
          "positive_sentiment": 0.9,
          "negative_sentiment": 0.09,
          "engagement_rate": 0.19,
          "impressions": 8000,
          "comments": 45,
          "shares": 30,
          "click_through_rate": 0.09,
          "average_likes": 90,
          "average_comments": 20
        },
        {
          "date": "2023-05-06",
          "media": 320,
          "follows": 320,
          "followed_by": 52,
          "reach": 5500,
          "positive_sentiment": 0.92,
          "negative_sentiment": 0.1,
          "engagement_rate": 0.2,
          "impressions": 8200,
          "comments": 47,
          "shares": 32,
          "click_through_rate": 0.1,
          "average_likes": 92,
          "average_comments": 22
        },
        {
          "date": "2023-05-07",
          "media": 330,
          "follows": 330,
          "followed_by": 55,
          "reach": 5700,
          "positive_sentiment": 0.94,
          "negative_sentiment": 0.11,
          "engagement_rate": 0.21,
          "impressions": 8400,
          "comments": 50,
          "shares": 34,
          "click_through_rate": 0.11,
          "average_likes": 94,
          "average_comments": 24
        },
        {
          "date": "2023-05-08",
          "media": 340,
          "follows": 340,
          "followed_by": 58,
          "reach": 5900,
          "positive_sentiment": 0.96,
          "negative_sentiment": 0.12,
          "engagement_rate": 0.22,
          "impressions": 8600,
          "comments": 52,
          "shares": 36,
          "click_through_rate": 0.12,
          "average_likes": 96,
          "average_comments": 26
        },
        {
          "date": "2023-05-09",
          "media": 350,
          "follows": 350,
          "followed_by": 60,
          "reach": 6100,
          "positive_sentiment": 0.98,
          "negative_sentiment": 0.13,
          "engagement_rate": 0.23,
          "impressions": 8800,
          "comments": 55,
          "shares": 38,
          "click_through_rate": 0.13,
          "average_likes": 98,
          "average_comments": 28
        },
        {
          "date": "2023-06-20",
          "media": 370,
          "follows": 370,
          "followed_by": 68,
          "reach": 6500,
          "positive_sentiment": 0.92,
          "negative_sentiment": 0.09,
          "engagement_rate": 0.18,
          "impressions": 9200,
          "comments": 42,
          "shares": 28,
          "click_through_rate": 0.09,
          "average_likes": 88,
          "average_comments": 18
        },
        {
          "date": "2023-06-25",
          "media": 380,
          "follows": 380,
          "followed_by": 70,
          "reach": 6700,
          "positive_sentiment": 0.95,
          "negative_sentiment": 0.11,
          "engagement_rate": 0.21,
          "impressions": 9400,
          "comments": 45,
          "shares": 30,
          "click_through_rate": 0.11,
          "average_likes": 94,
          "average_comments": 24
        },
        {
          "date": "2023-06-30",
          "media": 390,
          "follows": 390,
          "followed_by": 72,
          "reach": 6900,
          "positive_sentiment": 0.98,
          "negative_sentiment": 0.13,
          "engagement_rate": 0.23,
          "impressions": 9600,
          "comments": 48,
          "shares": 32,
          "click_through_rate": 0.13,
          "average_likes": 98,
          "average_comments": 28
        }
      ]
      
  },
]
